# Generated by Django 5.0.7 on 2024-11-15 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('food_item', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
            ],
        ),
    ]
